import './globals.css'
import { Montserrat } from 'next/font/google'
import fs from "fs";


const montserrat = Montserrat({
  subsets: ['latin'],
  weight:'variable',
  display:'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full bg-white'>
      <body className={montserrat.className}>
        {children}
      </body>
    </html>
  )
}
